"""Photo-based vehicle visuals + URDF. Python 3 + numpy; independent of the map.

Reference design is 0.200 m long. Measurements are not available: these are
photographic proportions, with an explicitly approximate four-wheel skid drive.
Run from any directory. No sandbox map or archive is generated by this script.
"""
from pathlib import Path
from collections import defaultdict
import base64, json, math, struct, xml.etree.ElementTree as ET
import numpy as np

PACKAGE=Path(__file__).resolve().parents[1]
WORKSPACE=PACKAGE.parents[1]
MESH_DIR=PACKAGE/'meshes'
R=.028; WW=.018; AXLE=.061; TRACK=.132
BODY_L=.200; BODY_W=.140; BODY_TOP=.034; PLATE_Z=.074
LIDAR=(.075,0,.059); CAMERA=(.102,0,.008)
COLORS={
    'shell':'#171a1d','plate':'#24272a','rubber':'#111315','edge':'#34383b',
    'teal':'#0ebac0','silver':'#9ca9ad','board':'#203b35','chip':'#131e22',
    'gold':'#b99954','cable_white':'#dddcd4','marker':'#b5b5ad',
    'lens':'#081b22','label':'#e6e2d6',
}
METALLIC={'teal':.76,'silver':.8,'gold':.72,'shell':.23,'plate':.22,'edge':.4}
ORIGINS={'base':(0,0,0),'wheel_left':(0,0,0),'wheel_right':(0,0,0),
         'lidar':LIDAR,'camera':CAMERA}
ASSEMBLY=[('base',(0,0,0)),('wheel_left',(AXLE,TRACK/2,0)),
          ('wheel_left',(-AXLE,TRACK/2,0)),('wheel_right',(AXLE,-TRACK/2,0)),
          ('wheel_right',(-AXLE,-TRACK/2,0)),('lidar',LIDAR),('camera',CAMERA)]

class Mesh:
    def __init__(self):self.v=[];self.f=[]
    def add(self,v,f):
        k=len(self.v);self.v.extend(tuple(float(x) for x in p) for p in v)
        self.f.extend(tuple(k+i for i in t) for t in f)
    def quad(self,p):self.add(p,[(0,1,2),(0,2,3)])
    def arrays(self):
        v=np.asarray(self.v,dtype=np.float32);f=np.asarray(self.f,dtype=np.uint32)
        n=np.zeros_like(v);cross=np.cross(v[f[:,1]]-v[f[:,0]],v[f[:,2]]-v[f[:,0]])
        for j in range(3):np.add.at(n,f[:,j],cross)
        n/=np.maximum(np.linalg.norm(n,axis=1),1e-15)[:,None]
        return v,f,n
M=defaultdict(Mesh)
def bucket(part,mat):return M[part,mat]
def area(p):return sum(p[i][0]*p[(i+1)%len(p)][1]-p[(i+1)%len(p)][0]*p[i][1] for i in range(len(p)))/2

def triangulate(p):
    ids=list(range(len(p)));result=[]
    def cr(a,b,c):return (b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0])
    while len(ids)>3:
        for q in range(len(ids)):
            a,b,c=ids[q-1],ids[q],ids[(q+1)%len(ids)]
            if cr(p[a],p[b],p[c])<=1e-14:continue
            if any(min(cr(p[a],p[b],p[j]),cr(p[b],p[c],p[j]),cr(p[c],p[a],p[j]))>=-1e-14 for j in ids if j not in (a,b,c)):continue
            result.append((a,b,c));ids.pop(q);break
        else:raise ValueError('Non-simple polygon')
    result.append(tuple(ids));return result

def rounded(x0,y0,x1,y1,r,n=8):
    points=[]
    for cx,cy,a in [(x1-r,y0+r,-math.pi/2),(x1-r,y1-r,0),(x0+r,y1-r,math.pi/2),(x0+r,y0+r,math.pi)]:
        points.extend((cx+r*math.cos(t),cy+r*math.sin(t)) for t in np.linspace(a,a+math.pi/2,n+1))
    return points

def circle(x,y,r,n=16):return [(x+r*math.cos(t),y+r*math.sin(t)) for t in np.linspace(0,math.tau,n,endpoint=False)]

def prism(points,z,height,part,mat,axes=None):
    p=list(points)
    if area(p)<0:p.reverse()
    faces=triangulate(p);count=len(p)
    v=[(x,y,h) for h in [z,z+height] for x,y in p]
    f=[(c,b,a) for a,b,c in faces]+[(a+count,b+count,c+count) for a,b,c in faces]
    for i in range(count):
        j=(i+1)%count;f.extend([(i,j,j+count),(i,j+count,i+count)])
    if axes is not None:v=[tuple(axes@np.asarray(q)) for q in v]
    bucket(part,mat).add(v,f)

def box(x,y,z,sx,sy,sz,part,mat):
    prism([(x-sx/2,y-sy/2),(x+sx/2,y-sy/2),(x+sx/2,y+sy/2),(x-sx/2,y+sy/2)],z,sz,part,mat)

def beam(a,b,r,part,mat,n=10,r2=None):
    a,b=np.asarray(a,float),np.asarray(b,float);axis=b-a;length=np.linalg.norm(axis)
    if length<1e-10:return
    axis/=length;ref=np.array([0,0,1]) if abs(axis[2])<.9 else np.array([1,0,0])
    u=np.cross(axis,ref);u/=np.linalg.norm(u);v=np.cross(axis,u);r2=r if r2 is None else r2
    pts=[tuple(c+rr*(u*math.cos(t)+v*math.sin(t))) for c,rr in [(a,r),(b,r2)] for t in np.linspace(0,math.tau,n,endpoint=False)]
    faces=[]
    for i in range(n):
        j=(i+1)%n;faces.extend([(i,j,n+j),(i,n+j,n+i)])
    faces.extend((0,i+1,i) for i in range(1,n-1));faces.extend((n,n+i,n+i+1) for i in range(1,n-1))
    bucket(part,mat).add(pts,faces)

def sphere(c,r,part,mat,n=16,rings=8):
    c=np.asarray(c);v=[tuple(c+[0,0,-r])]
    for p in np.linspace(-math.pi/2,math.pi/2,rings+1)[1:-1]:
        v.extend(tuple(c+r*np.array([math.cos(p)*math.cos(t),math.cos(p)*math.sin(t),math.sin(p)])) for t in np.linspace(0,math.tau,n,endpoint=False))
    v.append(tuple(c+[0,0,r]));f=[]
    for j in range(n):f.append((0,1+(j+1)%n,1+j))
    for i in range(rings-2):
        for j in range(n):
            a=1+i*n+j;b=1+i*n+(j+1)%n;f.extend([(a,b,b+n),(a,b+n,a+n)])
    last=1+(rings-2)*n
    for j in range(n):f.append((last+j,last+(j+1)%n,len(v)-1))
    bucket(part,mat).add(v,f)

def tube(points,r,part,mat,n=7):
    # Shared rings keep cable/trim normals smooth, without caps at every segment.
    points=np.asarray(points,float)
    if len(points)<2:return
    closed=np.linalg.norm(points[0]-points[-1])<1e-10
    verts=[];faces=[];previous=None
    for i,p in enumerate(points):
        if closed and i in (0,len(points)-1):tangent=points[1]-points[-2]
        else:tangent=points[min(i+1,len(points)-1)]-points[max(i-1,0)]
        tangent/=np.linalg.norm(tangent)
        if previous is None:
            ref=np.array([0,0,1]) if abs(tangent[2])<.9 else np.array([1,0,0])
            u=np.cross(tangent,ref)
        else:u=previous-tangent*np.dot(previous,tangent)
        u/=np.linalg.norm(u);v=np.cross(tangent,u);previous=u
        verts.extend(tuple(p+r*(u*math.cos(t)+v*math.sin(t))) for t in np.linspace(0,math.tau,n,endpoint=False))
    for i in range(len(points)-1):
        for k in range(n):
            a=i*n+k;b=i*n+(k+1)%n;faces.extend([(a,b,b+n),(a,b+n,a+n)])
    bucket(part,mat).add(verts,faces)
    if not closed:
        for start,reverse in [(0,True),((len(points)-1)*n,False)]:
            cap=[(0,k,k+1) for k in range(1,n-1)]
            if reverse:cap=[(c,b,a) for a,b,c in cap]
            bucket(part,mat).add(verts[start:start+n],cap)

def bezier(p,n=18):
    a,b,c,d=np.asarray(p,float)
    return [(1-t)**3*a+3*(1-t)**2*t*b+3*(1-t)*t*t*c+t**3*d for t in np.linspace(0,1,n)]

def plate_holes(outer,holes,z,thickness,part='base',mat='plate'):
    """Exact polygonal holes using vertical trapezoid decomposition, no booleans."""
    rings=[outer]+holes;edges=[(np.asarray(a),np.asarray(b)) for ring in rings for a,b in zip(ring,ring[1:]+ring[:1]) if abs(a[0]-b[0])>1e-12]
    xs=sorted(set(round(p[0],10) for ring in rings for p in ring))
    def yy(edge,x):
        a,b=edge;return a[1]+(x-a[0])*(b[1]-a[1])/(b[0]-a[0])
    for x0,x1 in zip(xs[:-1],xs[1:]):
        if x1-x0<1e-9:continue
        mid=(x0+x1)/2;hits=[e for e in edges if min(e[0][0],e[1][0])<mid<max(e[0][0],e[1][0])]
        hits.sort(key=lambda e:yy(e,mid));assert len(hits)%2==0
        for low,high in zip(hits[::2],hits[1::2]):
            p=[(x0,yy(low,x0)),(x1,yy(low,x1)),(x1,yy(high,x1)),(x0,yy(high,x0))]
            clean=[]
            for pt in p:
                if not clean or math.dist(pt,clean[-1])>1e-10:clean.append(pt)
            if len(clean)>1 and math.dist(clean[0],clean[-1])<1e-10:clean.pop()
            if len(clean)<3 or area(clean)<1e-14:continue
            f=triangulate(clean)
            bucket(part,mat).add([(x,y,z+thickness) for x,y in clean],f)
            bucket(part,mat).add([(x,y,z) for x,y in clean],[(c,b,a) for a,b,c in f])
    for k,ring in enumerate(rings):
        ring=list(ring)
        if (area(ring)>0)!=(k==0):ring.reverse()
        for a,b in zip(ring,ring[1:]+ring[:1]):
            bucket(part,mat).quad([(*a,z),(*b,z),(*b,z+thickness),(*a,z+thickness)])

def rev_y(profile,part,mat,n=48):
    v=[(r*math.cos(t),y,r*math.sin(t)) for y,r in profile for t in np.linspace(0,math.tau,n,endpoint=False)]
    f=[]
    for i in range(len(profile)):
        j=(i+1)%len(profile)
        for a in range(n):
            b=(a+1)%n;f.extend([(i*n+a,i*n+b,j*n+b),(i*n+a,j*n+b,j*n+a)])
    bucket(part,mat).add(v,[(c,b,a) for a,b,c in f])

def build_wheel(part,side):
    rev_y([(-.009,.0198),(-.009,.0248),(-.006,.0275),(.006,.0275),(.009,.0248),(.009,.0198)],part,'rubber')
    # Low tread blocks: the very outside remains the physical 28 mm radius.
    for a in np.linspace(0,math.tau,40,endpoint=False):
        for y in [-.0033,.0033]:
            d=.050;pts=[]
            for rad in [.02725,.028]:
                pts.extend([(rad*math.cos(t),yy,rad*math.sin(t)) for t,yy in [(a-d,y-.0027),(a+d,y-.0027),(a+d+.03,y+.0027),(a-d+.03,y+.0027)]])
            faces=[(0,2,1),(0,3,2),(4,5,6),(4,6,7),(0,1,5),(0,5,4),(1,2,6),(1,6,5),(2,3,7),(2,7,6),(3,0,4),(3,4,7)]
            bucket(part,'rubber').add(pts,[(c,b,a) for a,b,c in faces])
    sy=side*.0095
    rev_y([(sy-.0007,.0188),(sy-.0007,.0214),(sy+.0007,.0214),(sy+.0007,.0188)],part,'teal')
    for a in np.linspace(0,math.tau,10,endpoint=False):
        outline=[]
        for r,t in [(.0044,a-.18),(.012,a-.03),(.020,a+.13),(.020,a+.27),(.011,a+.13),(.0044,a+.18)]:outline.append((r*math.cos(t),r*math.sin(t)))
        # The X/Z spoke plane is extruded along -Y, a proper rigid rotation.
        transform=np.array([[1,0,0],[0,0,-1],[0,1,0]])
        prism(outline,-sy-.0006,.0012,part,'teal',transform)
    beam((0,sy-side*.002,0),(0,sy+side*.001,0),.005,part,'teal',n=24)
    beam((0,sy+side*.001,0),(0,sy+side*.0018,0),.0027,part,'silver',n=16)
    for a in np.linspace(0,math.tau,5,endpoint=False):
        x,z=.0036*math.cos(a),.0036*math.sin(a)
        beam((x,sy,z),(x,sy+side*.0011,z),.00055,part,'silver',n=6)

def build_body():
    outline=rounded(-BODY_L/2,-BODY_W/2,BODY_L/2,BODY_W/2,.020,n=12)
    # Sample shell walls through the wheel arches so the tyres are exposed.
    sampled=[]
    for a,b in zip(outline,outline[1:]+outline[:1]):
        count=max(1,math.ceil(math.dist(a,b)/.0015))
        sampled.extend(tuple(np.asarray(a)+(np.asarray(b)-a)*t/count) for t in range(count))
    lower=[]
    for x,y in sampled:
        z=-.016
        if abs(y)>.060:
            for ax in [-AXLE,AXLE]:
                if abs(x-ax)<.031:z=max(z,math.sqrt(max(0,.031**2-(x-ax)**2)))
        lower.append(z)
    for i,(x,y) in enumerate(sampled):
        j=(i+1)%len(sampled);xx,yy=sampled[j]
        bucket('base','shell').quad([(x,y,lower[i]),(xx,yy,lower[j]),(xx,yy,BODY_TOP),(x,y,BODY_TOP)])
    vents=[]
    for sy in [-1,1]:
        for j in range(6):
            x=.040+j*.005;half=.009-abs(j-2.5)*.0017
            vents.append(rounded(x-.0011,sy*.044-half,x+.0011,sy*.044+half,.0010,n=4))
    plate_holes(outline,vents,BODY_TOP-.0015,.0015,'base','shell')
    tube([(*p,BODY_TOP+.0005) for p in outline+[outline[0]]],.0006,'base','edge',n=5)
    # Central undertray; kept inset so the wheel openings remain real openings.
    box(0,0,-.018,.171,.102,.008,'base','shell')
    for side in [-1,1]:
        for j in range(4):
            pts=bezier([(-.027,side*.0704,.005-j*.004),(-.005,side*.0705,.019-j*.005),(.015,side*.0705,.011-j*.004),(.026,side*.0704,.008-j*.004)],14)
            tube(pts,.0006,'base','edge',n=5)
    def front_x(y):return .080+math.sqrt(max(0,.020**2-max(0,abs(y)-.050)**2)) if abs(y)>.050 else .100
    for side in [-1,1]:
        points=[(side*y,z) for y,z in [(.041,.018),(.057,.016),(.067,.011),(.068,-.004),(.063,-.011),(.044,-.011),(.041,-.007)]]
        # Follow the rounded nose rather than cutting straight chords through it.
        points.append(points[0]);pts=[]
        for a,b in zip(points[:-1],points[1:]):
            for t in np.linspace(0,1,max(2,math.ceil(math.dist(a,b)/.001)),endpoint=False):
                y,z=np.asarray(a)*(1-t)+np.asarray(b)*t
                pts.append((front_x(y)+.0010,y,z))
        pts.append(pts[0])
        tube(pts,.0011,'base','teal',n=8)
    # Back charge socket, tether and the dark rear panel.
    beam((-.0998,0,.012),(-.102,0,.012),.0040,'base','silver',n=20)
    beam((-.1017,0,.012),(-.1024,0,.012),.0028,'base','rubber',n=20)
    beam((-.102,0,.010),(-.102,0,-.010),.00065,'base','rubber',n=6)
    beam((-.1018,0,-.010),(-.1028,0,-.010),.0026,'base','rubber',n=14)
    for x in [-.087,.091]:
        for y in [-.050,.050]:
            beam((x,y,BODY_TOP),(x,y,BODY_TOP+.001),.0020,'base','edge',n=10)

def build_upper():
    outer=rounded(-.102,-.073,.024,.073,.015,n=8)
    holes=[rounded(-.052,-.028,-.014,.026,.002,n=4),rounded(-.008,-.038,.016,-.010,.002,n=4)]
    for x,y,sx,sy in [(-.072,.039,.022,.006),(-.072,-.039,.022,.006),(-.013,.045,.023,.006),(-.042,-.057,.018,.006)]:
        holes.append(rounded(x-sx/2,y-sy/2,x+sx/2,y+sy/2,.0028,n=5))
    for x,y in [(-.085,.014),(-.084,-.015),(.009,.061),(.008,-.062),(-.055,.060),(-.055,-.064)]:holes.append(circle(x,y,.0015,12))
    plate_holes(outer,holes,PLATE_Z-.0025,.0025)
    for x in [-.078,-.008]:
        for y in [-.063,.063]:box(x,y,BODY_TOP,.010 if x>-.04 else .004,.003,PLATE_Z-BODY_TOP-.0025,'base','plate')
    # Curving front hoop; a flat band at each side surrounds the lidar.
    for side in [-1,1]:
        pts=bezier([(.019,side*.070,PLATE_Z),(.051,side*.073,.074),(.106,side*.068,.047),(.094,side*.063,.035)],24)
        left=[];right=[]
        for i,p in enumerate(pts):
            d=pts[min(i+1,len(pts)-1)]-pts[max(0,i-1)]
            normal=np.array([-d[2],0,d[0]]);normal/=np.linalg.norm(normal)
            left.append(p+normal*.004);right.append(p-normal*.004)
        for i in range(len(pts)-1):
            for shift,reverse in [(-.0012,True),(.0012,False)]:
                q=[left[i]+[0,shift,0],left[i+1]+[0,shift,0],right[i+1]+[0,shift,0],right[i]+[0,shift,0]]
                if reverse:q.reverse()
                bucket('base','plate').quad(q)
            for index,curve in enumerate([left,right]):
                q=[curve[i]+[0,-.0012,0],curve[i+1]+[0,-.0012,0],curve[i+1]+[0,.0012,0],curve[i]+[0,.0012,0]]
                if index:q.reverse()
                bucket('base','plate').quad(q)
    box(.095,0,.0335,.010,.126,.0025,'base','plate')
    # Five grey optical tracking balls on short sockets.
    for x,y in [(-.084,.056),(-.069,-.059),(.011,.055),(.014,-.056),(.016,.005)]:
        beam((x,y,PLATE_Z),(x,y,PLATE_Z+.003),.0025,'base','edge',n=10)
        sphere((x,y,PLATE_Z+.0085),.0057,'base','marker')
    # Visible computer board, stacked modules, ports and fasteners.
    box(-.035,0,.052,.066,.051,.0016,'base','board')
    box(-.032,0,.054,.018,.020,.004,'base','chip')
    for x in [-.058,-.020]:
        for y in [-.021,.021]:
            beam((x,y,BODY_TOP),(x,y,.055),.0013,'base','gold',n=7)
    for j in range(10):
        box(-.060+j*.0045,.019,.054,.002,.003,.001,'base','silver')
        box(-.060+j*.0045,-.019,.054,.002,.003,.001,'base','gold')
    for x in [-.047,-.031]:
        box(x,-.030,.046,.012,.014,.010,'base','silver')
        box(x,-.0372,.048,.008,.0008,.005,'base','chip')
    box(-.009,.010,.040,.028,.028,.006,'base','chip')
    for x in [-.023,-.017,-.011,-.005]:box(x,.010,.046,.001,.025,.004,'base','edge')
    cables=[([(-.046,-.038,.050),(-.039,-.092,.025),(.034,-.075,.030),(.012,-.037,.052)],.0018,'cable_white'),
            ([(-.025,-.035,.050),(-.005,-.071,.023),(.050,-.047,.022),(.028,-.021,.043)],.0012,'cable_white'),
            ([(-.054,.023,.055),(-.030,.078,.062),(.051,.053,.053),(.072,.006,.046)],.0009,'rubber'),
            ([(-.018,-.02,.052),(.008,-.06,.037),(.048,-.043,.037),(.065,-.01,.039)],.0008,'rubber')]
    for p,r,mat in cables:tube(bezier(p,28),r,'base',mat,n=7)
    # Rear number plate: geometric digit 2, so no external fonts or textures.
    box(-.097,0,.037,.003,.021,.033,'base','plate')
    box(-.0988,0,.047,.0005,.017,.018,'base','label')
    digit=[(-.005,.061),(-.001,.063),(.004,.061),(.004,.058),(-.005,.051),(.005,.051)]
    tube([(-.0992,-y,z) for y,z in digit],.0007,'base','shell',n=6)

def build_sensors():
    # Mesh coordinates are local to the matching sensor link, not body-relative.
    beam((0,0,-.025),(0,0,-.010),.016,'lidar','shell',n=48)
    beam((0,0,-.011),(0,0,.004),.0123,'lidar','shell',n=48)
    beam((0,0,-.0025),(0,0,.0025),.01255,'lidar','lens',n=48)
    beam((0,0,.004),(0,0,.0047),.0120,'lidar','edge',n=40)
    for y in [-.014,.014]:
        box(-.002,y,-.025,.030,.005,.002,'lidar','plate')
        beam((.007,y,-.023),(.007,y,-.022),.0010,'lidar','silver',n=8)
    # Front camera points along +X; the optical frame is supplied separately.
    beam((-.004,0,0),(.0005,0,0),.0083,'camera','rubber',n=40)
    beam((.0005,0,0),(.0012,0,0),.0068,'camera','edge',n=40)
    beam((.0013,0,0),(.0015,0,0),.0056,'camera','lens',n=40)
    for start in [-1.34,1.80]:
        points=[(.0005,.0102*math.cos(t),.0102*math.sin(t)) for t in np.linspace(start,start+2.68,28)]
        tube(points,.0008,'camera','teal',n=7)

def rgb(mat):return [int(COLORS[mat][i:i+2],16)/255 for i in (1,3,5)]

def write_obj(path,v,f,n,mat):
    with path.open('w',encoding='utf-8',newline='\n') as out:
        out.write(f'mtllib vehicle.mtl\no {path.stem}\nusemtl {mat}\n')
        for p in v:out.write('v %.8f %.8f %.8f\n'%tuple(p))
        for p in n:out.write('vn %.8f %.8f %.8f\n'%tuple(p))
        for t in f:out.write('f '+' '.join(f'{int(i)+1}//{int(i)+1}' for i in t)+'\n')

def elem(parent,tag,**attrs):return ET.SubElement(parent,tag,{k:str(v) for k,v in attrs.items()})
def xyz(v):return ' '.join(f'{a:.9g}' for a in v)
def origin(parent,position=(0,0,0),rpy=(0,0,0)):elem(parent,'origin',xyz=xyz(position),rpy=xyz(rpy))
def inertial(link,mass,size,position=(0,0,0),cylinder=False):
    node=elem(link,'inertial');origin(node,position);elem(node,'mass',value=mass)
    if cylinder:
        r,w=size;ix=mass*(3*r*r+w*w)/12;iy=mass*r*r/2;iz=ix
    else:
        x,y,z=size;ix=mass*(y*y+z*z)/12;iy=mass*(x*x+z*z)/12;iz=mass*(x*x+y*y)/12
    elem(node,'inertia',ixx=ix,ixy=0,ixz=0,iyy=iy,iyz=0,izz=iz)
def box_collision(link,name,position,size):
    c=elem(link,'collision',name=name);origin(c,position);elem(elem(c,'geometry'),'box',size=xyz(size))
def visuals(link,part):
    for p,mat in M:
        if p!=part:continue
        node=elem(link,'visual',name=f'{part}_{mat}');origin(node)
        elem(elem(node,'geometry'),'mesh',filename=f'package://dongfeng_description/meshes/{part}_{mat}.obj')
        material=elem(node,'material',name='vehicle_'+mat);elem(material,'color',rgba=xyz(rgb(mat)+[1]))

def write_urdf():
    robot=ET.Element('robot',{'name':'dongfeng_car'})
    robot.append(ET.Comment('Generated by scripts/generate_vehicle.py. X forward, Y left, Z up. File keeps the .xacro name for launch compatibility. Sensors are geometry/frames only.'))
    base=elem(robot,'link',name='base_link');visuals(base,'base')
    box_collision(base,'body_envelope',(0,0,.009),(.194,.136,.050))
    box_collision(base,'upper_platform',(-.039,0,.07275),(.126,.146,.0025))
    for side in [-1,1]:box_collision(base,'support_'+str(side),(-.008,side*.063,.053),(.010,.003,.038))
    inertial(base,1.20,(.20,.14,.10),(0,0,.021))
    wheels=[]
    for side,sign in [('left',1),('right',-1)]:
        for axle,x in [('rear',-AXLE),('front',AXLE)]:
            # Keep the existing left/right joint names on the rear axle.
            suffix=side if axle=='rear' else side+'_front'
            name=f'wheel_{suffix}_link';joint=f'wheel_{suffix}_joint'
            link=elem(robot,'link',name=name);visuals(link,'wheel_'+side)
            c=elem(link,'collision',name='rolling_tyre');origin(c,rpy=(-math.pi/2,0,0))
            elem(elem(c,'geometry'),'cylinder',radius=R,length=WW)
            inertial(link,.060,(R,WW),cylinder=True)
            j=elem(robot,'joint',name=joint,type='continuous');elem(j,'parent',link='base_link');elem(j,'child',link=name)
            origin(j,(x,sign*TRACK/2,0));elem(j,'axis',xyz='0 1 0')
            g=elem(robot,'gazebo',reference=name)
            for key,value in [('mu1',1.0),('mu2',1.0),('kp',1000000),('kd',100)]:elem(g,key).text=str(value)
            wheels.append((side,joint))
    for part,pos,mass in [('lidar',LIDAR,.050),('camera',CAMERA,.012)]:
        link=elem(robot,'link',name=part+'_link');visuals(link,part)
        c=elem(link,'collision',name=part+'_housing')
        if part=='lidar':
            origin(c,(0,0,-.010));elem(elem(c,'geometry'),'cylinder',radius=.016,length=.030)
            inertial(link,mass,(.032,.032,.030),(0,0,-.010))
        else:
            origin(c,rpy=(0,math.pi/2,0));elem(elem(c,'geometry'),'cylinder',radius=.009,length=.005)
            inertial(link,mass,(.005,.018,.018))
        j=elem(robot,'joint',name=part+'_joint',type='fixed');elem(j,'parent',link='base_link');elem(j,'child',link=part+'_link');origin(j,pos)
    elem(robot,'link',name='camera_optical_frame')
    j=elem(robot,'joint',name='camera_optical_joint',type='fixed');elem(j,'parent',link='camera_link');elem(j,'child',link='camera_optical_frame')
    origin(j,(.0015,0,0),(-math.pi/2,0,-math.pi/2))
    g=elem(robot,'gazebo');drive=elem(g,'plugin',filename='gz-sim-diff-drive-system',name='gz::sim::systems::DiffDrive')
    for side,joint in wheels:elem(drive,side+'_joint').text=joint
    for key,value in [('wheel_separation',TRACK),('wheel_radius',R),('topic','/cmd_vel'),('odom_topic','/odom'),('tf_topic','/tf'),('frame_id','odom'),('child_frame_id','base_link'),('odom_publish_frequency',50),('min_linear_velocity',-.25),('max_linear_velocity',.25),('min_angular_velocity',-1.2),('max_angular_velocity',1.2),('min_linear_acceleration',-.6),('max_linear_acceleration',.6),('min_angular_acceleration',-2.4),('max_angular_acceleration',2.4)]:elem(drive,key).text=str(value)
    pub=elem(g,'plugin',filename='gz-sim-joint-state-publisher-system',name='gz::sim::systems::JointStatePublisher')
    elem(pub,'topic').text='/joint_states';elem(pub,'update_rate').text='50'
    ET.indent(robot);ET.ElementTree(robot).write(PACKAGE/'urdf/dongfeng_car.urdf.xacro',encoding='utf-8',xml_declaration=True)

def assembled_arrays():
    items=[]
    for idx,(part,offset) in enumerate(ASSEMBLY):
        for (p,mat),mesh in M.items():
            if p==part:
                v,f,n=mesh.arrays();items.append((f'{part}_{idx}_{mat}',part,mat,v+np.asarray(offset,dtype=np.float32),f,n))
    return items

def write_glb(items,path):
    binary=bytearray();views=[];access=[];meshes=[];nodes=[];materials=[];matids={}
    def pack(a,type_,component):
        while len(binary)%4:binary.append(0)
        start=len(binary);binary.extend(a.tobytes());views.append({'buffer':0,'byteOffset':start,'byteLength':a.nbytes})
        acc={'bufferView':len(views)-1,'componentType':component,'count':len(a),'type':type_}
        if type_=='VEC3':acc.update(min=a.min(axis=0).tolist(),max=a.max(axis=0).tolist())
        access.append(acc);return len(access)-1
    for name,part,mat,v,f,n in items:
        if mat not in matids:
            srgb=rgb(mat);linear=[c/12.92 if c<=.04045 else ((c+.055)/1.055)**2.4 for c in srgb]
            matids[mat]=len(materials);materials.append({'name':mat,'pbrMetallicRoughness':{'baseColorFactor':linear+[1],'metallicFactor':METALLIC.get(mat,0),'roughnessFactor':.28 if mat=='teal' else .7},'doubleSided':False})
        vi=pack(v.astype('<f4'),'VEC3',5126);ni=pack(n.astype('<f4'),'VEC3',5126);fi=pack(f.astype('<u4').reshape(-1),'SCALAR',5125)
        meshes.append({'name':name,'primitives':[{'attributes':{'POSITION':vi,'NORMAL':ni},'indices':fi,'material':matids[mat]}]});nodes.append({'name':name,'mesh':len(meshes)-1})
    root=len(nodes);nodes.append({'name':'dongfeng_car','rotation':[-math.sqrt(.5),0,0,math.sqrt(.5)],'children':list(range(root))})
    doc={'asset':{'version':'2.0','generator':'Photo-based Dongfeng car'},'scene':0,'scenes':[{'nodes':[root]}],'nodes':nodes,'meshes':meshes,'materials':materials,'buffers':[{'byteLength':len(binary)}],'bufferViews':views,'accessors':access}
    js=json.dumps(doc,separators=(',',':')).encode();js+=b' '*((-len(js))%4);binary+=b'\0'*((-len(binary))%4)
    path.write_bytes(struct.pack('<III',0x46546c67,2,28+len(js)+len(binary))+struct.pack('<II',len(js),0x4e4f534a)+js+struct.pack('<II',len(binary),0x004e4942)+binary)

def export():
    MESH_DIR.mkdir(parents=True,exist_ok=True)
    for (part,mat),mesh in M.items():
        v,f,n=mesh.arrays();assert np.isfinite(v).all()
        areas=np.linalg.norm(np.cross(v[f[:,1]]-v[f[:,0]],v[f[:,2]]-v[f[:,0]]),axis=1)
        assert np.all(areas>1e-13),(part,mat,float(areas.min()))
        write_obj(MESH_DIR/f'{part}_{mat}.obj',v,f,n,mat)
    text=[]
    for mat in COLORS:text.append(f'newmtl {mat}\nKd '+xyz(rgb(mat))+f'\nKa 0.2 0.2 0.2\nKs {"0.7 0.7 0.7" if mat in METALLIC else "0.05 0.05 0.05"}\nNs {80 if mat=="teal" else 20}\n')
    (MESH_DIR/'vehicle.mtl').write_text('\n'.join(text),encoding='utf-8')
    write_urdf();items=assembled_arrays()
    output=WORKSPACE/'previews/vehicle'
    export_dir=WORKSPACE/'exports/vehicle'
    report_dir=WORKSPACE/'reports/vehicle'
    for directory in (output,export_dir,report_dir):
        directory.mkdir(parents=True,exist_ok=True)
    data=[]
    for name,part,mat,v,f,n in items:
        enc=lambda a:base64.b64encode(a.tobytes()).decode('ascii')
        data.append({'name':name,'part':part,'material':mat,'color':COLORS[mat],'metalness':METALLIC.get(mat,0),'p':enc(v.astype('<f4')),'i':enc(f.astype('<u4')),'n':enc(n.astype('<f4'))})
    (output/'vehicle-data.json').write_text(json.dumps({'meshes':data,'wheel_radius':R,'sensors':{'lidar':LIDAR,'camera':CAMERA}},separators=(',',':')),encoding='utf-8')
    write_glb(items,export_dir/'dongfeng_car.glb')
    allv=np.concatenate([a[3] for a in items]);report={'visual_triangles':sum(len(a[4]) for a in items),'visual_mesh_files':len(M),'bounds_min_m':allv.min(axis=0).tolist(),'bounds_max_m':allv.max(axis=0).tolist(),'wheel_radius_m':R,'wheelbase_m':2*AXLE,'track_m':TRACK,'body_length_m':BODY_L,'body_width_m':BODY_W,'total_mass_kg':1.502,'sensors':'Visual models and frames only; no camera or lidar data yet.','dimensional_basis':'Existing 0.20 m length and supplied photographs, not measured.'}
    (report_dir/'geometry_report.json').write_text(json.dumps(report,indent=2),encoding='utf-8');print(json.dumps(report,indent=2))

if __name__=='__main__':
    build_body();build_upper();build_wheel('wheel_left',1);build_wheel('wheel_right',-1);build_sensors();export()
